name: default action
on:
    push:
      branches:
        - "master"

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "testing github actions"
          date